### ISSUE TITLE
支持查询参数

### ISSUE THREAD

**Issue by QingWei-Li** [ElementUI/issue-generator#1]
例如

- `https://eleme-issue.surge.sh/#/en-US?repo=elemefe/element`
- `https://eleme-issue.surge.sh/#/en-US?repo=elemefe/mint-ui`
- `https://eleme-issue.surge.sh/#/en-US?repo=elemefe/mint-ui&type=bug`

进入页面后默认选中参数里的内容

**Comment by iamkun** [comment]
done
